image: node:10.4.0 # Should match .nvmrc content

stages:
  - install
  - tests
  - build
  - deploy

# Instal stage

npm_install:
  tags: [shared-ci-docker]
  stage: install
  script:
    - npm ci

# Tests stage

npm_test:
  tags: [shared-ci-docker]
  stage: tests
  script:
    - npm ci
    - npm test

npm_run_lint:
  tags: [shared-ci-docker]
  stage: tests
  script:
    - npm ci
    - npm run lint

# Build stage

npm_run_build:
  tags: [shared-ci-docker]
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    expire_in: 1 week
    name: "build_${CI_COMMIT_SHA}"
    paths:
      - build

# Deploy stage

npm_run_deploy:
  tags: [shared-ci-docker]
  stage: deploy
  when: manual
  script:
    - echo 'Hello World' # TODO
  dependencies:
    - npm_run_build
