image: node:10.4.0 # Should match .nvmrc content

stages:
  - install
  - tests
  - build
  - deploy

# Instal stage

npm_install:
  stage: install
  script:
    - npm --version
    - npm set registry=http://10.1.0.5:4873/
    - npm ci
  artifacts:
    expire_in: 1 day
    name: "node_modules_${CI_COMMIT_SHA}"
    paths:
      - node_modules

# Tests stage

npm_test:
  stage: tests
  script:
    - npm test
  dependencies:
    - npm_install

npm_run_lint:
  stage: tests
  script:
    - npm run lint
  dependencies:
    - npm_install

# Build stage

npm_run_build:
  stage: build
  script:
    - npm run build
  artifacts:
    expire_in: 1 week
    name: "build_${CI_COMMIT_SHA}"
    paths:
      - build
  dependencies:
    - npm_install

# Deploy stage

npm_run_deploy:
  stage: deploy
  when: manual
  script:
    - echo 'Hello World' # TODO
  dependencies:
    - npm_run_build
