image: node:10.6.0 # Should match .nvmrc content

stages:
  - install
  - tests
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - node --version
  - npm --version
  - ls -alh

# Install stage

npm_install:
  tags: [shared-ci-docker]
  stage: install
  script:
    - npm run ci_if_nolock
  artifacts:
    paths:
      - node_modules
    expire_in: 3 hours
    name: "node_modules-$(sha1sum package-lock.json | cut -c1-7)"

# Tests stage

npm_test:
  tags: [shared-ci-docker]
  stage: tests
  script:
    - npm test -- --coverage
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

npm_run_lint:
  tags: [shared-ci-docker]
  stage: tests
  script:
    - npm run lint

# Build stage

npm_run_build:
  tags: [shared-ci-docker]
  stage: build
  script:
    - npm run build
  artifacts:
    expire_in: 2 days
    name: "build-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}"
    paths:
      - build

# Deploy stage

npm_run_deploy:
  tags: [shared-ci-docker]
  variables:
    GIT_STRATEGY: none
  stage: deploy
  when: manual
  script:
    - echo 'Hello World' # TODO
  dependencies:
    - npm_run_build
